avipagt/avipagt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from avipagt import settings

urlpatterns = [
                  path('jet/', include('jet.urls', 'jet')),
                  path('admin/', admin.site.urls),
                  path('', include('person.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)
admin.site.site_header = u'Administración de projectSyO'
admin.site.site_title = u'Sitio de administración'

avipagt/person/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from person.views import AsignarListView, AsignarACreate, ActualizarAUpdate, \
    RegistrarGuiaCreate, IndexGuiaView, PagosGuiaView, AgendaUpdate, ListPersonsView

urlpatterns = [
    path('registrar/', RegistrarGuiaCreate.as_view(), name="registrar-create"),
    path('actualizarA/<int:pk>/', ActualizarAUpdate.as_view(), name="actualizarA-update"),
    path('actualizar-agenda/<int:pk>/', AgendaUpdate.as_view(), name="actualizar-agenda"),
    path('asignarA/', AsignarACreate.as_view(), name="asignarA-create"),
    path('asignar/', AsignarListView.as_view(), name="asignar-list"),
    path('persons/', ListPersonsView.as_view(), name="persons-list"),
    path('index-guia/', IndexGuiaView.as_view(), name="index_guia"),
    path('pagos-guia/', PagosGuiaView.as_view(), name="pagos_guia"),
    path('', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
]

avipagt/operatingAgency/models.py
from django.db import models


# Create your models here.
class OperatingAgency(models.Model):
    business_name = models.CharField(max_length=100)
    legal_representative = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'operatingAgency'
        verbose_name_plural = 'operatingAgencys'

    def __str__(self):
        return self.business_name

avipagt/person/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Person(models.Model):
    SECRETARY = 'secretary'
    TOUR_GUIDE = 'tour guide'
    ROL = ((TOUR_GUIDE, TOUR_GUIDE), (SECRETARY, SECRETARY))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    identification_card = models.PositiveIntegerField()
    phone = models.PositiveIntegerField()
    adress = models.CharField(max_length=45)
    date_of_birth = models.DateField()
    rol = models.CharField(choices=ROL, max_length=45)
    professional_card = models.CharField(max_length=4)

    class Meta:
        verbose_name = 'person'
        verbose_name_plural = 'persons'

    def __str__(self):
        return self.user.first_name

avipagt/schedule/models.py
from django.db import models

# Create your models here.
from operatingAgency.models import OperatingAgency
from person.models import Person


class Schedule(models.Model):
    operating_agency = models.ForeignKey(OperatingAgency, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    start_date = models.DateField()
    ending_date = models.DateField()
    payment = models.BooleanField(default=False)
    payment_dispo = models.BooleanField(default=False)
    cantNationals = models.IntegerField(blank=True, null=True)
    cantForeigns = models.IntegerField(blank=True, null=True)

    class Meta:
        verbose_name = 'schedule'
        verbose_name_plural = 'shedules'

    def __bool__(self):
        return self.payment

avipagt/operatingAgency/views.py
from django.shortcuts import render

# Create your views here.

avipagt/person/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect

# Create your views here.
from django.shortcuts import redirect
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import UpdateView, CreateView

from person.models import Person
from schedule.models import Schedule


class IndexGuiaView(ListView):
    template_name = 'usuarioGuia/index.html'
    model = Schedule

    def get_queryset(self):
        queryset = super(IndexGuiaView, self).get_queryset()
        # Get the q GET parameter
        queryset = queryset.filter(person__user=self.request.user)
        q = self.request.GET.get('q')
        # q = q.replace(" ", "+")
        if q is None:
        # Return the base queryset
            return queryset
        # Return a filtered queryset
        return queryset

class PagosGuiaView(ListView):
    template_name = 'usuarioGuia/Pagos.html'
    model = Schedule

    def get_queryset(self):
        queryset = super(PagosGuiaView, self).get_queryset()
        # Get the q GET parameter
        queryset = queryset.filter(person__user=self.request.user,payment=True)
        q = self.request.GET.get('q')
        # q = q.replace(" ", "+")
        if q is None:
        # Return the base queryset
            return queryset
        # Return a filtered queryset
        return queryset


class AsignarListView(ListView):
    template_name = 'usuarioSecretaria/Asignar.html'
    model = Schedule
    queryset = Schedule.objects.all()

    def dispatch(self, request, *args, **kwargs):
        # check if there is some video onsite
        if not Person.objects.filter(rol="secretary",user=request.user).exists():
            return redirect('/index-guia')
        else:
            return super(AsignarListView, self).dispatch(request, *args, **kwargs)


class AsignarACreate(CreateView):
    template_name = 'usuarioSecretaria/AsignarA.html'
    model = Schedule
    fields = ['person', 'operating_agency', 'start_date', 'ending_date', 'cantNationals',
              'cantForeigns', ]
    success_url = "/asignar"


class ListPersonsView(ListView):
    template_name = 'usuarioSecretaria/Actualizar.html'
    model = Person
    # rol = Person.objects.filter(rol='tour guide')
    queryset = Person.objects.all()

class AgendaUpdate(UpdateView):
    template_name = 'usuarioSecretaria/ActualizarA.html'
    model = Schedule
    fields = ['payment', 'payment_dispo',]
    success_url = "/asignar/"
    def get_context_data(self, **kwargs):
        data = super(AgendaUpdate, self).get_context_data()
        data["sin_name"] = True
        return data

class ActualizarAUpdate(UpdateView):
    template_name = 'usuarioSecretaria/ActualizarA.html'
    model = Person
    fields = ['phone', 'adress', 'date_of_birth', 'professional_card']
    success_url = "/persons/"

    def get_context_data(self, **kwargs):
        data = super(ActualizarAUpdate, self).get_context_data()
        person = Person.objects.get(id=self.kwargs.get("pk"))
        user = User.objects.get(person=person)
        data["nombre"] = user.first_name
        data["apellido"] = user.last_name
        return data

    def form_valid(self, form):
        print(self.kwargs.get("pk"))
        person = Person.objects.get(id=self.kwargs.get("pk"))
        user = User.objects.get(person=person)
        user.first_name = self.request.POST.get('first_name')
        user.last_name = self.request.POST.get('last_name')
        user.save()
        # form.instance.user = user
        return super(ActualizarAUpdate, self).form_valid(form)


class RegistrarGuiaCreate(CreateView):
    template_name = 'usuarioSecretaria/Registrar.html'
    model = Person
    fields = ['identification_card', 'phone', 'adress', 'date_of_birth',
              'professional_card']
    success_url = "/persons/"

    def form_valid(self, form):
        # print(dir(form))
        print(self.request.POST.get('first_name'))
        user = User(username=form.instance.identification_card,first_name=self.request.POST.get('first_name'),
                    last_name=self.request.POST.get('last_name'))
        user.save()
        form.instance.user = user
        return super(RegistrarGuiaCreate, self).form_valid(form)

avipagt/schedule/views.py
from django.shortcuts import render

# Create your views here.

avipagt/person/templates/usuarioGuia/Pagos.html
<!DOCTYPE html>
<html>
<head>
    <title>Asociacion de Guias Turisticos</title>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1, maximun-scale=1, minimun-scale=1">
    <link rel="shortcut icon" href="/static/usuarioGuia/img/guias1.png"/>
    <link rel="stylesheet" href="/static/usuarioGuia/css/guia.css">
    <link rel="stylesheet" href="/static/usuarioGuia/css/fontello.css">
    <link rel="stylesheet" href="/static/usuarioGuia/css/Estilos.css">
    <link rel="stylesheet" href="/static/usuarioGuia/css/Tabla.css">
</head>
<body>
<header>
    <div class="contenedor">
        <h1 class="icon-child">Asociacion de Guias Turisticos</h1>
        <input type="checkbox" id="menu-bar">
        <label class="icon-menu" for="menu-bar"></label>
        <nav class="menu">

            <a href="/index-guia/">Agenda</a>
            <a href="#">Pagos</a>
            <a href="/logout/">Cerrar Sesion</a>


        </nav>
    </div>
</header>

<main>
    <section id="banner">
        <img src="/static/usuarioGuia/img/FondoInicioGuia.jpg">
        <div class="contenedor">
            <br><br><br><br>
            <h2>&nbsp;&nbsp;Pagos</h2>
            <section id="blog">

                <div id="main-container">

                    <table>
                        <thead>
                        <tr>
                            <th>Empresa</th>
                            <th>Fecha Inicio</th>
                            <th>Fecha Fin</th>
                            <th>Pago Disponible</th>
                            <th>Cobrado</th>
                        </tr>
                        </thead>
                        {% for a in object_list %}
                            <tr>
                                <td>{{ a.operating_agency.business_name }}</td>
                                <td>{{a.start_date}}</td>
                                <td>{{a.ending_date}}</td>
                                <td>{% if a.payment_dispo %}SI{% else %}NO{% endif %}</td>
                                <td>{% if a.payment %}SI{% else %}NO{% endif %}</td>
                                \

                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </section>

        </div>
    </section>


</main>
</body>
</html>

avipagt/person/templates/usuarioGuia/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Asociacion de Guias Turisticos</title>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1, maximun-scale=1, minimun-scale=1">
    <link rel="shortcut icon" href="/static/usuarioGuia/img/guias1.png"/>
    <link rel="stylesheet" href=/static/usuarioGuia/css/guia.css">
    <link rel="stylesheet" href="/static/usuarioGuia/css/fontello.css">
    <link rel="stylesheet" href="/static/usuarioGuia/css/Estilos.css">
    <link rel="stylesheet" href="/static/usuarioGuia/css/Tabla.css">
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBfmsm7wa4J4ueL6XTtZMq_u9V-DcOz2ng"></script>
    <script src="/static/usuarioGuia/JavaScrips/Web.js"></script>
</head>
<body>
<header>
    <div class="contenedor">
        <h1 class="icon-child">Asociacion de Guias Turisticos</h1>
        <input type="checkbox" id="menu-bar">
        <label class="icon-menu" for="menu-bar"></label>
        <nav class="menu">
            <a href="#">Agenda</a>
            <a href="/pagos-guia/">Pagos</a>
            <a href="/logout/">Cerrar Sesion</a>
        </nav>
    </div>
</header>

<main>
    <section id="banner">
        <img src="/static/usuarioGuia/img/FondoInicioGuia.jpg">
        <div class="contenedor">
            <br><br><br>
            <h2>&nbsp;&nbsp;Agenda</h2>
            <section id="blog">

                <div id="main-container">

                    <table>
                        <thead>
                        <tr>
                            <th>Empresa</th>
                            <th>Fecha Inicio</th>
                            <th>Fecha Fin</th>
                        </tr>
                        </thead>
                        {% for a in object_list %}
                        <tr>
                            <td>{{ a.operating_agency.business_name }}</td>
                            <td>{{a.start_date}}</td>
                            <td>{{a.ending_date}}</td>
                        </tr>
                        {% endfor %}

                    </table>

                    <button onclick="Mapa()">Mostrar ubicación</button>

                    <div id="map"></div>
                </div>


            </section>
        </div>
    </section>


</main>
</body>
</html>

avipagt/person/templates/usuarioGuia/prueba.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Geolocalizacion</title>
	<style>
		#map{
			margin: 20px;
		}
	</style>
</head>
<body>
	<button onclick="findMe()">Mostrar ubicación</button>
	<div id="map"></div>
	
	<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"></script>
	<script>
		function findMe(){
			var output = document.getElementById('map');

			// Verificar si soporta geolocalizacion
			if (navigator.geolocation) {
				output.innerHTML = "<p>Tu navegador soporta Geolocalizacion</p>";
			}else{
				output.innerHTML = "<p>Tu navegador no soporta Geolocalizacion</p>";
			}

			//Obtenemos latitud y longitud
			function localizacion(posicion){

				var latitude = 2.183292;
				var longitude = -73.786166;

				var imgURL = "https://maps.googleapis.com/maps/api/staticmap?center="+latitude+","+longitude+"&size=600x300&markers=color:red%7C"+latitude+","+longitude+"&key=AIzaSyB82qZsTeeAFVGoDm7zlzQGhKmuw3iGEI4";

				output.innerHTML ="<img src='"+imgURL+"'>";

				

			}

			function error(){
				output.innerHTML = "<p>No se pudo obtener tu ubicación</p>";

			}

			navigator.geolocation.getCurrentPosition(localizacion,error);

		}


	</script>
</body>
</html>

avipagt/person/templates/usuarioSecretaria/Actualizar.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Asociacion de Guias Turisticos</title>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1, maximun-scale=1, minimun-scale=1">
    <link rel="shortcut icon" href="/static/usuarioSecretaria/img/guias1.png"/>
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/guia1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/fontello1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/Estilos1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/Tabla1.css">
</head>
<body>
<header>
    <div class="contenedor">
        <h1 class="icon-child">Asociacion de Guias Turisticos</h1>
        <input type="checkbox" id="menu-bar">
        <label class="icon-menu" for="menu-bar"></label>
        <nav class="menu">
            <a href="{% url 'asignar-list' %}">Asignar</a>
            <a href="#">Guias Disponibles</a>
            <a href="{% url 'registrar-create' %}">Registrar nuevo guia</a>
{#            <a href="Actualizar.html">Actualizar informacion de un guia</a>#}
{#            <a href="Pago.html">Pagos</a>#}
            <a href="../registration/login.html">Cerrar Sesion</a>


        </nav>
    </div>
</header>

<main>
    <section id="banner">
{#        <img src="img/macarenanoche.png">#}
        <div class="contenedor">
            <br><br><br>
            <h2>&nbspGuias Disponibles</h2>
            <section id="blog">

                <div id="main-container">

                    <table>
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Cedula</th>
                            <th>TP</th>
                            <th>Celular</th>
                            <th>Direccion</th>
                        </tr>
                        </thead>

                        {% for  person in person_list %}
                            <tr>
{#                                <td>#}
{#                                    <a#}
{#                                            href="{% url 'actualizar-update' person.pk %}"#}
{#                                    >#}
{#                                        {{ person.id}}#}
{#                                    </a>#}
{#                                </td>#}
                                <td>
                                    <a
                                            href="{% url 'actualizarA-update' person.pk %}"
                                    >{{ person.user.first_name }}</a>
                                </td>
                                <td>{{ person.user.last_name }}</td>
                                <td>{{ person.identification_card }}</td>
                                <td>{{ person.adress}}</td>
                                <td>{{ person.phone }}</td>
                                <td>{{ person.professional_card }}</td>
                            </tr>
                        {% endfor %}
{#                        <tr>#}
{#                            <td><a href="ActualizarB.html">BYRON STEWAR</a></td>#}
{#                            <td>CUBIDES ROMERO</td>#}
{#                            <td>1121913825</td>#}
{#                            <td>1964</td>#}
{#                            <td>3115505891</td>#}
{#                            <td>PENDIENTE</td>#}
{#                        </tr>#}

                    </table>
                </div>
            </section>

        </div>
    </section>


</main>
</body>
</html>

avipagt/person/templates/usuarioSecretaria/ActualizarA.html
<!DOCTYPE html>
<html>
<head>
    <title>Asociacion de Guias Turisticos</title>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1, maximun-scale=1, minimun-scale=1">
    <link rel="shortcut icon" href="/static/usuarioSecretaria/img/guias1.png"/>
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/guia1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/fontello1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/Estilos1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/Tabla1.css">
    <script src="JavaScrips/ValidarCamposR.js"></script>

</head>
<body>
<header>
    <div class="contenedor">
        <h1 class="icon-child">Asociacion de Guias Turisticos</h1>
        <input type="checkbox" id="menu-bar">
        <label class="icon-menu" for="menu-bar"></label>
        <nav class="menu">

            <a href="{% url 'asignar-list' %}">Asignar</a>
            <a href="{% url 'persons-list' %}">Guias Disponibles</a>
            <a href="{% url 'registrar-create' %}">Registrar nuevo guia</a>
            <a href="/logout/">Cerrar Sesion</a>
        </nav>
    </div>
</header>

<main>
    <section id="bannerRegistrar">
        <img src="/static/usuarioSecretaria/img/macarenanoche.png">
        <div class="contenedor">


            <form method="post"  class="form Registrar" >
                {% csrf_token %}
                <h2>&nbsp;&nbsp;Actualizar informacion de guia</h2>
                <br><br>
                {% if not sin_name %}
                <label for="first_name">Nombre:</label>
                <input type="text" name="first_name"  id="first_name" value="{{ nombre }}">
                <label for="last_name">Apellidos:</label>
                <input type="text" name="last_name"  id="last_name" value="{{ apellido }}">
                {% endif %}
                {{ form }}
                <br><br>


                <input type="submit" value="Actualizar">

            </form>


        </div>
    </section>

</main>
</body>
</html>

avipagt/person/templates/usuarioSecretaria/Asignar.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Asociacion de Guias Turisticos</title>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1, maximun-scale=1 , minimun-scale=1">
    <link rel="shortcut icon" href="/static/usuarioSecretaria/img/guias1.png"/>
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/guia1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/fontello1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/Estilos1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/Tabla1.css">
</head>
<body>
<header>
    <div class="contenedor">
        <h1 class="icon-child">Asociacion de Guias Turisticos</h1>
        <input type="checkbox" id="menu-bar">
        <label class="icon-menu" for="menu-bar"></label>
        <nav class="menu">
            <a href="{% url 'asignar-list' %}">Asignar</a>
            <a href="{% url 'persons-list' %}">Guias Disponibles</a>
            <a href="{% url 'registrar-create' %}">Registrar nuevo guia</a>
{#            <a href="{% url 'actualizar-list' %}">Actualizar informacion de un guia</a>#}
{#            <a href="Pago.html">Pagos</a>#}
            <a href="/logout/">Cerrar Sesion</a>
        </nav>
    </div>
</header>

<main>
    <section id="banner">
        <div class="contenedor">
            <h2>Asignar Tour</h2>

            <section id="blog">
                <a href="/asignarA/">Agregar agenda <img src="/static/usuarioSecretaria/img/add.png" style="height: 25px; width: 25px"></a>
                <div id="main-container">
                    <table>
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Contacto</th>
                            <th>Empresa</th>
                            <th>Fecha Inicio</th>
                            <th>Fecha Fin</th>
                            <th>Disponible para pago</th>
                            <th>Pagada</th>
                        </tr>
                        </thead>
                        {% for schedule in schedule_list %}
                            <tr>
                                <td>
                                    <a
                                            href="{% url 'actualizar-agenda' schedule.pk %}"
                                    >{{ schedule.person.user.first_name }}</a>
                                </td>
                                <td>{{ schedule.person.user.last_name }}</td>
                                <td>{{ schedule.person.phone }}</td>
                                <td>{{ schedule.operating_agency.business_name }}</td>
                                <td>{{ schedule.start_date }}</td>
                                <td>{{ schedule.ending_date }}</td>
                                <td>{% if schedule.payment_dispo %}SI{% else %}NO{% endif %}</td>
                                <td>{% if schedule.payment %}SI{% else %}NO{% endif %}</td>
                            </tr>
                        {% endfor %}

                    </table>
                </div>
            </section>

        </div>
    </section>


</main>
</body>
</html>

avipagt/person/templates/usuarioSecretaria/AsignarA.html
<!DOCTYPE html>
<html>
<head>
    <title>Asociacion de Guias Turisticos</title>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1, maximun-scale=1, minimun-scale=1">
    <link rel="shortcut icon" href="/static/usuarioSecretaria/img/guias1.png"/>
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/guia1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/fontello1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/Estilos1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/Tabla1.css">
    <script src="JavaScrips/ValidarCamposR.js"></script>
</head>
<body>
<header>
    <div class="contenedor">
        <h1 class="icon-child">Asociacion de Guias Turisticos</h1>
        <input type="checkbox" id="menu-bar">
        <label class="icon-menu" for="menu-bar"></label>
        <nav class="menu">

             <a href="{% url 'asignar-list' %}">Asignar</a>
            <a href="{% url 'persons-list' %}">Guias Disponibles</a>
            <a href="{% url 'registrar-create' %}">Registrar nuevo guia</a>
{#            <a href="{% url 'actualizar-list' %}">Actualizar informacion de un guia</a>#}
{#            <a href="Pago.html">Pagos</a>#}
            <a href="/logout/">Cerrar Sesion</a>
        </nav>
    </div>
</header>

<main>
    <section id="bannerRegistrar">
        <img src="/static/usuarioSecretaria/img/macarenanoche.png">

        <div class="contenedor">

            <form method="post" class="form Registrar">
                {% csrf_token %}
                <h2>&nbsp;&nbsp;Asignar Tour</h2>
                <br><br>
                {{ form.as_p }}
                <br><br>


                <input type="submit" value="Asignar">

            </form>


        </div>
    </section>

</main>
</body>
</html>

avipagt/person/templates/usuarioSecretaria/Pago.html
<!DOCTYPE html>
<html>
<head>
    <title>Asociacion de Guias Turisticos</title>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1, maximun-scale=1, minimun-scale=1">
    <link rel="shortcut icon" href="/static/usuarioSecretaria/img/guias1.png"/>
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/guia1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/fontello1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/Estilos1.css">
    <link rel="stylesheet" href="/static/usuarioSecretaria/CSS/Tabla1.css">
    <script src="JavaScrips/ValidarCamposR.js"></script>
</head>
<body>
<header>
    <div class="contenedor">
        <h1 class="icon-child">Asociacion de Guias Turisticos</h1>
        <input type="checkbox" id="menu-bar">
        <label class="icon-menu" for="menu-bar"></label>
        <nav class="menu">

            <a href="Asignar.html">Guias Disponibles</a>
            <a href="Registrar.html">Registrar nuevo guia</a>
            <a href="Actualizar.html">Actualizar informacion de un guia</a>
            <a href="Pago.html">Pagos</a>
            <a href="../registration/login.html">Cerrar Sesion</a>
        </nav>
    </div>
</header>

<main>
    <section id="bannerRegistrar">
        <img src="img/macarenanoche.png">
        <div class="contenedor">


            <form action="index.html" method="POST" class="form Registrar" onsubmit="return ValidarCamposR();">
                <h2>&nbsp;&nbsp;Notificar Pago</h2>
                <br><br>
                <label for="nombre">Codigo de Tour a pagar</label>
                <input type="text" id="Nombre" name="nombre" placeholder="">
                <br><br>
                <label for="apellido">Nombre de Guia encargado</label>
                <input type="text" id="Apellido" name="apellido" placeholder="">
                <br><br>
                <label for="cedula">Cedula</label>
                <input type="text" id="Cedula" name="cedula" placeholder="">
                <br><br>
                <label for="tp">TP</label>
                <input type="text" id="TP" name="tp" placeholder="">
                <br><br>
                <label for="celular">Total cancelado</label>
                <input type="text" id="Celular" name="celular" placeholder="">
                <br><br>
                <label for="direccion">Fecha</label>
                <input type="date" id="Direccion" name="direccion" placeholder="">
                <br><br>


                <input type="submit" value="Enviar">

            </form>


        </div>
    </section>


</main>
</body>
</html>